name: weather-analyzer
version: 0.1.0.0
license: BSD3
author: karapuznikus
maintainer: armagedonwot@gmail.com
copyright: 2025 karapuznikus

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

# Исполняемый файл (ваша программа с main)
executables:
  weather-analyzer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weather-analyzer # ссылка на библиотеку этого же проекта

# Тесты (пока не нужны)
tests:
  weather-analyzer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weather-analyzer